# Generated by Django 4.2.16 on 2026-01-29 10:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('travellers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traveller',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created'),
        ),
        migrations.AlterField(
            model_name='traveller',
            name='dob',
            field=models.DateField(blank=True, help_text='Date of birth', null=True),
        ),
        migrations.AlterField(
            model_name='traveller',
            name='email',
            field=models.EmailField(blank=True, help_text='Email address', max_length=254),
        ),
        migrations.AlterField(
            model_name='traveller',
            name='first_name',
            field=models.CharField(help_text='First name', max_length=100),
        ),
        migrations.AlterField(
            model_name='traveller',
            name='gender',
            field=models.CharField(help_text='Gender', max_length=10),
        ),
        migrations.AlterField(
            model_name='traveller',
            name='last_name',
            field=models.CharField(help_text='Last name', max_length=100),
        ),
        migrations.AlterField(
            model_name='traveller',
            name='passport_expiry',
            field=models.DateField(blank=True, help_text='Passport expiry date', null=True),
        ),
        migrations.AlterField(
            model_name='traveller',
            name='passport_number',
            field=models.CharField(blank=True, help_text='Passport number', max_length=50),
        ),
        migrations.AlterField(
            model_name='traveller',
            name='phone',
            field=models.CharField(blank=True, help_text='Phone number', max_length=15),
        ),
        migrations.AlterField(
            model_name='traveller',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated'),
        ),
        migrations.AlterField(
            model_name='traveller',
            name='user',
            field=models.ForeignKey(help_text='Related user', on_delete=django.db.models.deletion.CASCADE, related_name='travellers', to=settings.AUTH_USER_MODEL),
        ),
    ]
