# Generated by Django 4.2.16 on 2026-01-29 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travellers', '0002_alter_traveller_created_at_alter_traveller_dob_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='traveller',
            name='city',
            field=models.CharField(blank=True, help_text='City', max_length=100),
        ),
        migrations.AddField(
            model_name='traveller',
            name='country',
            field=models.CharField(blank=True, help_text='Country', max_length=100),
        ),
        migrations.AddField(
            model_name='traveller',
            name='frequent_flyer_airline',
            field=models.CharField(blank=True, help_text='Frequent flyer airline', max_length=100),
        ),
        migrations.AddField(
            model_name='traveller',
            name='frequent_flyer_number',
            field=models.CharField(blank=True, help_text='Frequent flyer number', max_length=50),
        ),
        migrations.AddField(
            model_name='traveller',
            name='passport_copy',
            field=models.ImageField(blank=True, help_text='Passport copy image', null=True, upload_to='travellers/passports/'),
        ),
        migrations.AddField(
            model_name='traveller',
            name='passport_issuing_country',
            field=models.CharField(blank=True, help_text='Passport issuing country', max_length=100),
        ),
        migrations.AddField(
            model_name='traveller',
            name='pincode',
            field=models.CharField(blank=True, help_text='Pin Code', max_length=20),
        ),
        migrations.AddField(
            model_name='traveller',
            name='state',
            field=models.CharField(blank=True, help_text='State', max_length=100),
        ),
    ]
