# Generated by Django 4.2.16 on 2026-01-29 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_is_phone_verified_user_otp_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_phone_verified',
            field=models.BooleanField(default=False, help_text="Designates whether the user's phone number is verified"),
        ),
        migrations.AlterField(
            model_name='user',
            name='otp_created_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the OTP was created', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='otp_token',
            field=models.CharField(blank=True, help_text='One Time Password token for verification', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(help_text="User's unique phone number", max_length=15, unique=True),
        ),
    ]
