# Generated by Django 4.2.16 on 2026-01-27 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='gst_percent',
            field=models.DecimalField(decimal_places=2, default=12.0, max_digits=5),
        ),
    ]
