# Generated by Django 4.2.16 on 2026-01-28 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_roomtypeimage_propertyimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='property',
            options={'verbose_name_plural': 'Properties'},
        ),
        migrations.AlterModelOptions(
            name='propertyimage',
            options={'ordering': ['order', 'created_at']},
        ),
        migrations.AlterModelOptions(
            name='roomtypeimage',
            options={'ordering': ['order', 'created_at']},
        ),
        migrations.RemoveField(
            model_name='property',
            name='rating',
        ),
        migrations.AddField(
            model_name='property',
            name='amenities',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='property',
            name='area',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='check_in_time',
            field=models.TimeField(default='14:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='check_out_time',
            field=models.TimeField(default='11:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='discount_percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='property',
            name='review_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='property',
            name='review_rating',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='rules',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='star_rating',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='propertyimage',
            name='alt_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='bedroom_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='booking_policy',
            field=models.TextField(default='No policy'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roomtype',
            name='is_entire_place',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='refund_policy',
            field=models.TextField(default='No policy'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roomtype',
            name='total_units',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roomtypeimage',
            name='alt_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('hotel', 'Hotel'), ('resort', 'Resort'), ('homestay', 'Homestay'), ('villa', 'Villa'), ('apartment', 'Apartment')], max_length=20),
        ),
        migrations.AlterField(
            model_name='propertyimage',
            name='image',
            field=models.ImageField(upload_to='properties/gallery/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='base_price',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='roomtypeimage',
            name='image',
            field=models.ImageField(upload_to='room_types/gallery/%Y/%m/'),
        ),
    ]
