# Generated by Django 4.2.16 on 2026-01-29 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_amenity_discount_remove_property_discount_percent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='allow_entire_place_booking',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='entire_place_max_guests',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='entire_place_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
