# Generated by Django 4.2.16 on 2026-01-29 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_property_allow_entire_place_booking_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amenity',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created'),
        ),
        migrations.AlterField(
            model_name='amenity',
            name='icon',
            field=models.ImageField(blank=True, help_text='Icon for the amenity', null=True, upload_to='amenities/icons/'),
        ),
        migrations.AlterField(
            model_name='amenity',
            name='name',
            field=models.CharField(help_text='Name of the amenity', max_length=255),
        ),
        migrations.AlterField(
            model_name='amenity',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='discount_type',
            field=models.CharField(choices=[('percentage', 'Percentage'), ('flat', 'Flat Amount')], help_text='Type of discount (Percentage or Flat Amount)', max_length=20),
        ),
        migrations.AlterField(
            model_name='discount',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this discount is active'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='name',
            field=models.CharField(help_text='Name of the discount', max_length=255),
        ),
        migrations.AlterField(
            model_name='discount',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='value',
            field=models.DecimalField(decimal_places=2, help_text='Value of the discount', max_digits=12),
        ),
        migrations.AlterField(
            model_name='property',
            name='allow_entire_place_booking',
            field=models.BooleanField(default=False, help_text='Allow booking the entire place'),
        ),
        migrations.AlterField(
            model_name='property',
            name='amenities',
            field=models.ManyToManyField(blank=True, help_text='Amenities available at the property', related_name='properties', to='properties.amenity'),
        ),
        migrations.AlterField(
            model_name='property',
            name='area',
            field=models.CharField(blank=True, help_text='Area or locality', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='check_in_time',
            field=models.TimeField(help_text='Check-in time'),
        ),
        migrations.AlterField(
            model_name='property',
            name='check_out_time',
            field=models.TimeField(help_text='Check-out time'),
        ),
        migrations.AlterField(
            model_name='property',
            name='city',
            field=models.CharField(help_text='City where the property is located', max_length=100),
        ),
        migrations.AlterField(
            model_name='property',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created'),
        ),
        migrations.AlterField(
            model_name='property',
            name='description',
            field=models.TextField(help_text='Detailed description of the property'),
        ),
        migrations.AlterField(
            model_name='property',
            name='discount',
            field=models.ForeignKey(blank=True, help_text='Applicable discount', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='properties', to='properties.discount'),
        ),
        migrations.AlterField(
            model_name='property',
            name='entire_place_max_guests',
            field=models.PositiveIntegerField(blank=True, help_text='Maximum guests for entire place booking', null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='entire_place_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price for booking the entire place', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='gst_percent',
            field=models.DecimalField(decimal_places=2, default=12.0, help_text='GST percentage applicable', max_digits=5),
        ),
        migrations.AlterField(
            model_name='property',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this property is active'),
        ),
        migrations.AlterField(
            model_name='property',
            name='name',
            field=models.CharField(help_text='Name of the property', max_length=255),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('hotel', 'Hotel'), ('resort', 'Resort'), ('homestay', 'Homestay'), ('villa', 'Villa'), ('apartment', 'Apartment')], help_text='Type of property', max_length=20),
        ),
        migrations.AlterField(
            model_name='property',
            name='review_count',
            field=models.PositiveIntegerField(default=0, help_text='Total number of reviews'),
        ),
        migrations.AlterField(
            model_name='property',
            name='review_rating',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Average review rating', max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='rules',
            field=models.TextField(blank=True, help_text='House rules for guests', null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='star_rating',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Star rating of the property', null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='state',
            field=models.CharField(help_text='State where the property is located', max_length=100),
        ),
        migrations.AlterField(
            model_name='property',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated'),
        ),
        migrations.AlterField(
            model_name='propertyimage',
            name='alt_text',
            field=models.CharField(blank=True, help_text='Alternative text for accessibility', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='propertyimage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created'),
        ),
        migrations.AlterField(
            model_name='propertyimage',
            name='image',
            field=models.ImageField(help_text='Image file', upload_to='properties/gallery/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='propertyimage',
            name='is_primary',
            field=models.BooleanField(default=False, help_text='Is this the primary image?'),
        ),
        migrations.AlterField(
            model_name='propertyimage',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Display order'),
        ),
        migrations.AlterField(
            model_name='propertyimage',
            name='property',
            field=models.ForeignKey(help_text='Related property', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='properties.property'),
        ),
        migrations.AlterField(
            model_name='propertyimage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated'),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='base_price',
            field=models.DecimalField(decimal_places=2, help_text='Base price per night', max_digits=12),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='bedroom_count',
            field=models.PositiveIntegerField(blank=True, help_text='Number of bedrooms', null=True),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='booking_policy',
            field=models.TextField(help_text='Policy for booking'),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created'),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='has_breakfast',
            field=models.BooleanField(default=False, help_text='Breakfast included'),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='is_entire_place',
            field=models.BooleanField(default=False, help_text='Is this an entire place booking?'),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='max_guests',
            field=models.PositiveIntegerField(help_text='Maximum number of guests'),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='name',
            field=models.CharField(help_text='Name of the room type', max_length=255),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='property',
            field=models.ForeignKey(help_text='Related property', on_delete=django.db.models.deletion.CASCADE, related_name='room_types', to='properties.property'),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='refund_policy',
            field=models.TextField(help_text='Policy for refunds'),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='total_units',
            field=models.PositiveIntegerField(help_text='Total number of units available'),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated'),
        ),
        migrations.AlterField(
            model_name='roomtypeimage',
            name='alt_text',
            field=models.CharField(blank=True, help_text='Alternative text for accessibility', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='roomtypeimage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created'),
        ),
        migrations.AlterField(
            model_name='roomtypeimage',
            name='image',
            field=models.ImageField(help_text='Image file', upload_to='room_types/gallery/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='roomtypeimage',
            name='is_primary',
            field=models.BooleanField(default=False, help_text='Is this the primary image?'),
        ),
        migrations.AlterField(
            model_name='roomtypeimage',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Display order'),
        ),
        migrations.AlterField(
            model_name='roomtypeimage',
            name='room_type',
            field=models.ForeignKey(help_text='Related room type', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='properties.roomtype'),
        ),
        migrations.AlterField(
            model_name='roomtypeimage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated'),
        ),
    ]
