# Generated by Django 4.2.16 on 2026-01-29 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0007_alter_amenity_created_at_alter_amenity_icon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='cancellation_policy',
            field=models.TextField(blank=True, help_text='Cancellation policy for the property', null=True),
        ),
    ]
