# Generated by Django 4.2.16 on 2026-01-30 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0008_property_cancellation_policy'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomtype',
            name='description',
            field=models.TextField(blank=True, help_text='Detailed description of the room type', null=True),
        ),
    ]
