# Generated by Django 4.2.16 on 2026-01-30 05:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0009_roomtype_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('name', models.CharField(help_text='Option name (e.g. Breakfast Included)', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Short description of this option', null=True)),
                ('base_price', models.DecimalField(decimal_places=2, help_text='Price for this option', max_digits=12)),
                ('has_breakfast', models.BooleanField(default=False, help_text='Breakfast included')),
                ('has_lunch', models.BooleanField(default=False, help_text='Lunch included')),
                ('has_dinner', models.BooleanField(default=False, help_text='Dinner included')),
                ('is_refundable', models.BooleanField(default=False, help_text='Is this option refundable?')),
                ('cancellation_policy', models.TextField(blank=True, help_text='Specific cancellation policy', null=True)),
                ('room_type', models.ForeignKey(help_text='Related room type', on_delete=django.db.models.deletion.CASCADE, related_name='options', to='properties.roomtype')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
