# Generated by Django 4.2.16 on 2026-01-30 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0010_roomoption'),
    ]

    operations = [
        migrations.CreateModel(
            name='FamousPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('name', models.CharField(help_text='Name of the famous place', max_length=255)),
                ('description', models.TextField(help_text='Detailed description of the place')),
                ('city', models.CharField(db_index=True, help_text='City where the place is located', max_length=100)),
                ('location', models.CharField(help_text='Specific location/address', max_length=255)),
                ('entry_fee', models.CharField(blank=True, help_text="Entry fee information (e.g., 'INR 15 per person')", max_length=255, null=True)),
                ('timings', models.CharField(blank=True, help_text='Opening and closing timings', max_length=255, null=True)),
                ('image', models.ImageField(blank=True, help_text='Image of the place', null=True, upload_to='famous_places/%Y/%m/')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this place is active')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
