# Generated by Django 4.2.16 on 2026-01-30 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0011_famousplace'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='famousplace',
            name='image',
        ),
    ]
