# Generated by Django 4.2.16 on 2026-01-30 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0012_remove_famousplace_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Latitude coordinate', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Longitude coordinate', max_digits=9, null=True),
        ),
    ]
