# Generated by Django 4.2.16 on 2026-01-28 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cabs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CabCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Cab Categories',
            },
        ),
        migrations.AlterModelOptions(
            name='cab',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='cab',
            name='cab_type',
        ),
        migrations.AddField(
            model_name='cab',
            name='driver_allowance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='cab',
            name='extra_km_fare',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cab',
            name='free_waiting_time_minutes',
            field=models.PositiveIntegerField(default=45),
        ),
        migrations.AddField(
            model_name='cab',
            name='fuel_type',
            field=models.CharField(choices=[('petrol', 'Petrol'), ('diesel', 'Diesel'), ('cng', 'CNG')], default='petrol', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cab',
            name='included_kms',
            field=models.PositiveIntegerField(default=0, help_text='Distance included in base price'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cab',
            name='is_ac',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='cab',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='cab',
            name='luggage_capacity',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='cab',
            name='price_per_km',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cab',
            name='title',
            field=models.CharField(default='Untitled', help_text='e.g. Sedan | Dzire, Etios or Similar', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cab',
            name='base_price',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='cab',
            name='capacity',
            field=models.PositiveIntegerField(help_text='Seating capacity'),
        ),
        migrations.CreateModel(
            name='CabPricingOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('option_type', models.CharField(choices=[('pay_now', 'Pay Now'), ('pay_later', 'Pay Later')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_default', models.BooleanField(default=False)),
                ('cab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_options', to='cabs.cab')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CabPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('cab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policies', to='cabs.cab')),
            ],
            options={
                'verbose_name_plural': 'Cab Policies',
            },
        ),
        migrations.CreateModel(
            name='CabInclusion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(max_length=255)),
                ('value', models.CharField(max_length=255)),
                ('is_included', models.BooleanField(default=True)),
                ('cab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inclusions', to='cabs.cab')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CabImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='cabs/gallery/%Y/%m/')),
                ('is_primary', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('cab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='cabs.cab')),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='CabBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pickup_location', models.CharField(max_length=255)),
                ('drop_location', models.CharField(max_length=255)),
                ('pickup_datetime', models.DateTimeField()),
                ('trip_type', models.CharField(choices=[('oneway', 'One Way'), ('roundtrip', 'Round Trip')], max_length=20)),
                ('total_distance_km', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('cab', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='cabs.cab')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='cab',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cabs', to='cabs.cabcategory'),
        ),
    ]
