# Generated by Django 4.2.16 on 2026-01-29 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cabs', '0002_cabcategory_alter_cab_options_remove_cab_cab_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cab',
            name='base_price',
            field=models.DecimalField(decimal_places=2, help_text='Base price for the cab', max_digits=12),
        ),
        migrations.AlterField(
            model_name='cab',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Category of the cab', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cabs', to='cabs.cabcategory'),
        ),
        migrations.AlterField(
            model_name='cab',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created'),
        ),
        migrations.AlterField(
            model_name='cab',
            name='driver_allowance',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Driver allowance per day', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='cab',
            name='extra_km_fare',
            field=models.DecimalField(decimal_places=2, help_text='Fare per extra kilometer', max_digits=10),
        ),
        migrations.AlterField(
            model_name='cab',
            name='free_waiting_time_minutes',
            field=models.PositiveIntegerField(default=45, help_text='Free waiting time in minutes'),
        ),
        migrations.AlterField(
            model_name='cab',
            name='fuel_type',
            field=models.CharField(choices=[('petrol', 'Petrol'), ('diesel', 'Diesel'), ('cng', 'CNG')], help_text='Type of fuel used', max_length=10),
        ),
        migrations.AlterField(
            model_name='cab',
            name='is_ac',
            field=models.BooleanField(default=True, help_text='Designates whether the cab has AC'),
        ),
        migrations.AlterField(
            model_name='cab',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether the cab is active'),
        ),
        migrations.AlterField(
            model_name='cab',
            name='luggage_capacity',
            field=models.PositiveIntegerField(default=2, help_text='Luggage capacity (number of bags)'),
        ),
        migrations.AlterField(
            model_name='cab',
            name='price_per_km',
            field=models.DecimalField(decimal_places=2, help_text='Price per kilometer', max_digits=10),
        ),
        migrations.AlterField(
            model_name='cab',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated'),
        ),
        migrations.AlterField(
            model_name='cabbooking',
            name='cab',
            field=models.ForeignKey(help_text='Related cab', on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='cabs.cab'),
        ),
        migrations.AlterField(
            model_name='cabbooking',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created'),
        ),
        migrations.AlterField(
            model_name='cabbooking',
            name='drop_location',
            field=models.CharField(help_text='Drop location', max_length=255),
        ),
        migrations.AlterField(
            model_name='cabbooking',
            name='pickup_datetime',
            field=models.DateTimeField(help_text='Date and time of pickup'),
        ),
        migrations.AlterField(
            model_name='cabbooking',
            name='pickup_location',
            field=models.CharField(help_text='Pickup location', max_length=255),
        ),
        migrations.AlterField(
            model_name='cabbooking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='pending', help_text='Status of the booking', max_length=20),
        ),
        migrations.AlterField(
            model_name='cabbooking',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, help_text='Total amount for the booking', max_digits=12),
        ),
        migrations.AlterField(
            model_name='cabbooking',
            name='total_distance_km',
            field=models.DecimalField(decimal_places=2, help_text='Total distance in km', max_digits=10),
        ),
        migrations.AlterField(
            model_name='cabbooking',
            name='trip_type',
            field=models.CharField(choices=[('oneway', 'One Way'), ('roundtrip', 'Round Trip')], help_text='Type of trip', max_length=20),
        ),
        migrations.AlterField(
            model_name='cabbooking',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated'),
        ),
        migrations.AlterField(
            model_name='cabcategory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created'),
        ),
        migrations.AlterField(
            model_name='cabcategory',
            name='description',
            field=models.TextField(blank=True, help_text='Description of the cab category', null=True),
        ),
        migrations.AlterField(
            model_name='cabcategory',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether the category is active'),
        ),
        migrations.AlterField(
            model_name='cabcategory',
            name='name',
            field=models.CharField(help_text='Name of the cab category', max_length=100),
        ),
        migrations.AlterField(
            model_name='cabcategory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated'),
        ),
        migrations.AlterField(
            model_name='cabimage',
            name='cab',
            field=models.ForeignKey(help_text='Related cab', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='cabs.cab'),
        ),
        migrations.AlterField(
            model_name='cabimage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created'),
        ),
        migrations.AlterField(
            model_name='cabimage',
            name='image',
            field=models.ImageField(help_text='Image file for the cab', upload_to='cabs/gallery/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='cabimage',
            name='is_primary',
            field=models.BooleanField(default=False, help_text='Designates whether this is the primary image'),
        ),
        migrations.AlterField(
            model_name='cabimage',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Ordering of the image'),
        ),
        migrations.AlterField(
            model_name='cabimage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated'),
        ),
        migrations.AlterField(
            model_name='cabinclusion',
            name='cab',
            field=models.ForeignKey(help_text='Related cab', on_delete=django.db.models.deletion.CASCADE, related_name='inclusions', to='cabs.cab'),
        ),
        migrations.AlterField(
            model_name='cabinclusion',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created'),
        ),
        migrations.AlterField(
            model_name='cabinclusion',
            name='is_included',
            field=models.BooleanField(default=True, help_text='Designates whether this is an inclusion'),
        ),
        migrations.AlterField(
            model_name='cabinclusion',
            name='label',
            field=models.CharField(help_text="Label of the inclusion (e.g., 'Parking Charges')", max_length=255),
        ),
        migrations.AlterField(
            model_name='cabinclusion',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated'),
        ),
        migrations.AlterField(
            model_name='cabinclusion',
            name='value',
            field=models.CharField(help_text="Value of the inclusion (e.g., 'Included')", max_length=255),
        ),
        migrations.AlterField(
            model_name='cabpolicy',
            name='cab',
            field=models.ForeignKey(help_text='Related cab', on_delete=django.db.models.deletion.CASCADE, related_name='policies', to='cabs.cab'),
        ),
        migrations.AlterField(
            model_name='cabpolicy',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created'),
        ),
        migrations.AlterField(
            model_name='cabpolicy',
            name='description',
            field=models.TextField(help_text='Description of the policy'),
        ),
        migrations.AlterField(
            model_name='cabpolicy',
            name='title',
            field=models.CharField(help_text='Title of the policy', max_length=255),
        ),
        migrations.AlterField(
            model_name='cabpolicy',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated'),
        ),
        migrations.AlterField(
            model_name='cabpricingoption',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Amount for the option', max_digits=12),
        ),
        migrations.AlterField(
            model_name='cabpricingoption',
            name='cab',
            field=models.ForeignKey(help_text='Related cab', on_delete=django.db.models.deletion.CASCADE, related_name='pricing_options', to='cabs.cab'),
        ),
        migrations.AlterField(
            model_name='cabpricingoption',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created'),
        ),
        migrations.AlterField(
            model_name='cabpricingoption',
            name='description',
            field=models.TextField(blank=True, help_text='Description of the option', null=True),
        ),
        migrations.AlterField(
            model_name='cabpricingoption',
            name='is_default',
            field=models.BooleanField(default=False, help_text='Designates whether this is the default option'),
        ),
        migrations.AlterField(
            model_name='cabpricingoption',
            name='option_type',
            field=models.CharField(choices=[('pay_now', 'Pay Now'), ('pay_later', 'Pay Later')], help_text='Type of pricing option', max_length=20),
        ),
        migrations.AlterField(
            model_name='cabpricingoption',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated'),
        ),
    ]
