# Generated by Django 4.2.16 on 2026-01-29 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0007_alter_amenity_created_at_alter_amenity_icon_and_more'),
        ('cabs', '0003_alter_cab_base_price_alter_cab_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cab',
            name='cancellation_policy',
            field=models.TextField(blank=True, help_text='Cancellation policy summary (e.g. Free till 1 hour of departure)', null=True),
        ),
        migrations.AddField(
            model_name='cab',
            name='discount',
            field=models.ForeignKey(blank=True, help_text='Applicable discount for the cab', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cabs', to='properties.discount'),
        ),
        migrations.AddField(
            model_name='cab',
            name='location',
            field=models.CharField(blank=True, help_text='Location where the cab is based (e.g. Sulthan Bathery)', max_length=255, null=True),
        ),
    ]
