# Generated by Django 4.2.16 on 2026-01-30 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabs', '0004_cab_cancellation_policy_cab_discount_cab_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='CabTransferType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('name', models.CharField(help_text='Name of the transfer type', max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Cab Transfer Type',
                'verbose_name_plural': 'Cab Transfer Types',
            },
        ),
        migrations.AddField(
            model_name='cab',
            name='transfer_types',
            field=models.ManyToManyField(blank=True, help_text='Supported transfer types (e.g., Airport, Outstation)', related_name='cabs', to='cabs.cabtransfertype'),
        ),
    ]
