# Generated by Django 4.2.16 on 2026-01-29 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodDestination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('name', models.CharField(help_text='Name of the food destination', max_length=255)),
                ('slug', models.SlugField(blank=True, help_text='Unique slug for the URL', max_length=255, unique=True)),
                ('location', models.CharField(help_text='Location (e.g., Sulthan Bathery, Wayanad)', max_length=255)),
                ('description', models.TextField(help_text='Detailed description of the food destination')),
                ('price_per_person', models.DecimalField(decimal_places=2, help_text='Price per person', max_digits=10)),
                ('rating', models.DecimalField(decimal_places=1, default=0.0, help_text='Average rating (0.0 to 5.0)', max_digits=3)),
                ('reviews_count', models.PositiveIntegerField(default=0, help_text='Total number of reviews')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this destination is active')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FoodDestinationImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('image', models.ImageField(help_text='Image of the food destination', upload_to='dining/gallery/%Y/%m/')),
                ('is_primary', models.BooleanField(default=False, help_text='Designates whether this is the primary image')),
                ('food_destination', models.ForeignKey(help_text='Related food destination', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='dining.fooddestination')),
            ],
            options={
                'ordering': ['-is_primary', '-created_at'],
            },
        ),
    ]
