# Generated by Django 4.2.16 on 2026-01-28 04:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_amenity_discount_remove_property_discount_percent_and_more'),
        ('packages', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='holidaypackage',
            options={'ordering': ['-created_at'], 'verbose_name': 'Holiday Package', 'verbose_name_plural': 'Holiday Packages'},
        ),
        migrations.AlterModelOptions(
            name='packageitinerary',
            options={'ordering': ['day_number', 'order'], 'verbose_name_plural': 'Package Itineraries'},
        ),
        migrations.RemoveField(
            model_name='holidaypackage',
            name='location',
        ),
        migrations.AddField(
            model_name='holidaypackage',
            name='discount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='holiday_packages', to='properties.discount'),
        ),
        migrations.AddField(
            model_name='holidaypackage',
            name='highlights',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='holidaypackage',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='holidaypackage',
            name='primary_location',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='holidaypackage',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='holidaypackage',
            name='review_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='holidaypackage',
            name='secondary_locations',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='holidaypackage',
            name='short_description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='holidaypackage',
            name='slug',
            field=models.SlugField(default=1, max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='holidaypackage',
            name='terms_and_conditions',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='packageitinerary',
            name='from_location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='packageitinerary',
            name='order',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='packageitinerary',
            name='stay_nights',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='packageitinerary',
            name='stay_property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='properties.property'),
        ),
        migrations.AddField(
            model_name='packageitinerary',
            name='to_location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='packageitinerary',
            name='transport_type',
            field=models.CharField(blank=True, choices=[('cab', 'Cab'), ('boat', 'Boat'), ('train', 'Train'), ('flight', 'Flight'), ('self', 'Self Drive')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='holidaypackage',
            name='base_price',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='holidaypackage',
            name='duration_days',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='holidaypackage',
            name='duration_nights',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='packageitinerary',
            name='day_number',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='packageitinerary',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='PackageTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transport_type', models.CharField(choices=[('cab', 'Cab'), ('boat', 'Boat'), ('train', 'Train'), ('flight', 'Flight')], max_length=20)),
                ('description', models.TextField()),
                ('itinerary_day', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers', to='packages.packageitinerary')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='packages.holidaypackage')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PackageInclusion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.TextField()),
                ('is_included', models.BooleanField(default=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inclusions', to='packages.holidaypackage')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PackageImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='packages/gallery/%Y/%m/')),
                ('is_primary', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='packages.holidaypackage')),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='PackageFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('feature_type', models.CharField(choices=[('sightseeing', 'Sightseeing'), ('stay', 'Stay'), ('transport', 'Transport'), ('meals', 'Meals')], max_length=20)),
                ('is_included', models.BooleanField(default=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='packages.holidaypackage')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PackageActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='packages/activities/%Y/%m/')),
                ('itinerary_day', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='packages.packageitinerary')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='packages.holidaypackage')),
            ],
            options={
                'verbose_name_plural': 'Package Activities',
            },
        ),
        migrations.CreateModel(
            name='PackageAccommodation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nights', models.PositiveSmallIntegerField()),
                ('meals_included', models.JSONField(blank=True, default=list, null=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accommodations', to='packages.holidaypackage')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.property')),
                ('room_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='properties.roomtype')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
