# Generated by Django 4.2.16 on 2026-01-28 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_alter_activity_options_activity_description_and_more'),
        ('cabs', '0002_cabcategory_alter_cab_options_remove_cab_cab_type_and_more'),
        ('houseboats', '0001_initial'),
        ('packages', '0002_alter_holidaypackage_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='packageactivity',
            name='activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='package_activities', to='activities.activity'),
        ),
        migrations.AddField(
            model_name='packageitinerary',
            name='stay_houseboat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='package_itineraries', to='houseboats.houseboat'),
        ),
        migrations.AddField(
            model_name='packagetransfer',
            name='cab_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='package_transfers', to='cabs.cabcategory'),
        ),
    ]
