# Generated by Django 4.2.16 on 2026-01-29 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('houseboats', '0002_alter_houseboat_base_price_per_night_and_more'),
        ('cabs', '0003_alter_cab_base_price_alter_cab_category_and_more'),
        ('properties', '0007_alter_amenity_created_at_alter_amenity_icon_and_more'),
        ('activities', '0003_alter_activity_base_price_alter_activity_created_at_and_more'),
        ('packages', '0003_packageactivity_activity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holidaypackage',
            name='base_price',
            field=models.DecimalField(decimal_places=2, help_text='Base price for the package', max_digits=12),
        ),
        migrations.AlterField(
            model_name='holidaypackage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created'),
        ),
        migrations.AlterField(
            model_name='holidaypackage',
            name='discount',
            field=models.ForeignKey(blank=True, help_text='Applicable discount for the package', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='holiday_packages', to='properties.discount'),
        ),
        migrations.AlterField(
            model_name='holidaypackage',
            name='duration_days',
            field=models.PositiveSmallIntegerField(help_text='Duration of the package in days'),
        ),
        migrations.AlterField(
            model_name='holidaypackage',
            name='duration_nights',
            field=models.PositiveSmallIntegerField(help_text='Duration of the package in nights'),
        ),
        migrations.AlterField(
            model_name='holidaypackage',
            name='highlights',
            field=models.JSONField(blank=True, default=list, help_text='List of package highlights', null=True),
        ),
        migrations.AlterField(
            model_name='holidaypackage',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether the package is active'),
        ),
        migrations.AlterField(
            model_name='holidaypackage',
            name='primary_location',
            field=models.CharField(help_text='Primary location of the package', max_length=255),
        ),
        migrations.AlterField(
            model_name='holidaypackage',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Average rating of the package', max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='holidaypackage',
            name='review_count',
            field=models.PositiveIntegerField(default=0, help_text='Total number of reviews'),
        ),
        migrations.AlterField(
            model_name='holidaypackage',
            name='secondary_locations',
            field=models.JSONField(blank=True, default=list, help_text='List of secondary locations', null=True),
        ),
        migrations.AlterField(
            model_name='holidaypackage',
            name='short_description',
            field=models.TextField(help_text='Brief summary of the package'),
        ),
        migrations.AlterField(
            model_name='holidaypackage',
            name='slug',
            field=models.SlugField(help_text='Unique slug for the package URL', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='holidaypackage',
            name='terms_and_conditions',
            field=models.TextField(help_text='Terms and conditions for the package'),
        ),
        migrations.AlterField(
            model_name='holidaypackage',
            name='title',
            field=models.CharField(help_text='Title of the holiday package', max_length=255),
        ),
        migrations.AlterField(
            model_name='holidaypackage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated'),
        ),
        migrations.AlterField(
            model_name='packageaccommodation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created'),
        ),
        migrations.AlterField(
            model_name='packageaccommodation',
            name='meals_included',
            field=models.JSONField(blank=True, default=list, help_text='List of included meals', null=True),
        ),
        migrations.AlterField(
            model_name='packageaccommodation',
            name='nights',
            field=models.PositiveSmallIntegerField(help_text='Number of nights'),
        ),
        migrations.AlterField(
            model_name='packageaccommodation',
            name='package',
            field=models.ForeignKey(help_text='Related holiday package', on_delete=django.db.models.deletion.CASCADE, related_name='accommodations', to='packages.holidaypackage'),
        ),
        migrations.AlterField(
            model_name='packageaccommodation',
            name='property',
            field=models.ForeignKey(help_text='Accommodation property', on_delete=django.db.models.deletion.CASCADE, to='properties.property'),
        ),
        migrations.AlterField(
            model_name='packageaccommodation',
            name='room_type',
            field=models.ForeignKey(blank=True, help_text='Type of room', null=True, on_delete=django.db.models.deletion.SET_NULL, to='properties.roomtype'),
        ),
        migrations.AlterField(
            model_name='packageaccommodation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated'),
        ),
        migrations.AlterField(
            model_name='packageactivity',
            name='activity',
            field=models.ForeignKey(blank=True, help_text='Related core activity', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='package_activities', to='activities.activity'),
        ),
        migrations.AlterField(
            model_name='packageactivity',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created'),
        ),
        migrations.AlterField(
            model_name='packageactivity',
            name='description',
            field=models.TextField(help_text='Description of the activity'),
        ),
        migrations.AlterField(
            model_name='packageactivity',
            name='image',
            field=models.ImageField(blank=True, help_text='Image for the activity', null=True, upload_to='packages/activities/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='packageactivity',
            name='itinerary_day',
            field=models.ForeignKey(blank=True, help_text='Related itinerary day', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='packages.packageitinerary'),
        ),
        migrations.AlterField(
            model_name='packageactivity',
            name='name',
            field=models.CharField(help_text='Name of the activity', max_length=255),
        ),
        migrations.AlterField(
            model_name='packageactivity',
            name='package',
            field=models.ForeignKey(help_text='Related holiday package', on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='packages.holidaypackage'),
        ),
        migrations.AlterField(
            model_name='packageactivity',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated'),
        ),
        migrations.AlterField(
            model_name='packagefeature',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created'),
        ),
        migrations.AlterField(
            model_name='packagefeature',
            name='feature_type',
            field=models.CharField(choices=[('sightseeing', 'Sightseeing'), ('stay', 'Stay'), ('transport', 'Transport'), ('meals', 'Meals')], help_text='Type of feature', max_length=20),
        ),
        migrations.AlterField(
            model_name='packagefeature',
            name='is_included',
            field=models.BooleanField(default=True, help_text='Designates whether the feature is included'),
        ),
        migrations.AlterField(
            model_name='packagefeature',
            name='package',
            field=models.ForeignKey(help_text='Related holiday package', on_delete=django.db.models.deletion.CASCADE, related_name='features', to='packages.holidaypackage'),
        ),
        migrations.AlterField(
            model_name='packagefeature',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated'),
        ),
        migrations.AlterField(
            model_name='packageimage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created'),
        ),
        migrations.AlterField(
            model_name='packageimage',
            name='image',
            field=models.ImageField(help_text='Image file for the package', upload_to='packages/gallery/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='packageimage',
            name='is_primary',
            field=models.BooleanField(default=False, help_text='Designates whether this is the primary image'),
        ),
        migrations.AlterField(
            model_name='packageimage',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Ordering of the image'),
        ),
        migrations.AlterField(
            model_name='packageimage',
            name='package',
            field=models.ForeignKey(help_text='Related holiday package', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='packages.holidaypackage'),
        ),
        migrations.AlterField(
            model_name='packageimage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated'),
        ),
        migrations.AlterField(
            model_name='packageinclusion',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created'),
        ),
        migrations.AlterField(
            model_name='packageinclusion',
            name='is_included',
            field=models.BooleanField(default=True, help_text='Designates whether this is an inclusion'),
        ),
        migrations.AlterField(
            model_name='packageinclusion',
            name='package',
            field=models.ForeignKey(help_text='Related holiday package', on_delete=django.db.models.deletion.CASCADE, related_name='inclusions', to='packages.holidaypackage'),
        ),
        migrations.AlterField(
            model_name='packageinclusion',
            name='text',
            field=models.TextField(help_text='Inclusion/Exclusion text'),
        ),
        migrations.AlterField(
            model_name='packageinclusion',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated'),
        ),
        migrations.AlterField(
            model_name='packageitinerary',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created'),
        ),
        migrations.AlterField(
            model_name='packageitinerary',
            name='day_number',
            field=models.PositiveSmallIntegerField(help_text='Day number of the itinerary'),
        ),
        migrations.AlterField(
            model_name='packageitinerary',
            name='description',
            field=models.TextField(help_text='Description of the itinerary day'),
        ),
        migrations.AlterField(
            model_name='packageitinerary',
            name='from_location',
            field=models.CharField(blank=True, help_text='Starting location', max_length=255),
        ),
        migrations.AlterField(
            model_name='packageitinerary',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, help_text='Ordering of the itinerary day'),
        ),
        migrations.AlterField(
            model_name='packageitinerary',
            name='package',
            field=models.ForeignKey(help_text='Related holiday package', on_delete=django.db.models.deletion.CASCADE, related_name='itinerary', to='packages.holidaypackage'),
        ),
        migrations.AlterField(
            model_name='packageitinerary',
            name='stay_houseboat',
            field=models.ForeignKey(blank=True, help_text='Stay houseboat for the day', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='package_itineraries', to='houseboats.houseboat'),
        ),
        migrations.AlterField(
            model_name='packageitinerary',
            name='stay_nights',
            field=models.PositiveSmallIntegerField(default=0, help_text='Number of nights staying'),
        ),
        migrations.AlterField(
            model_name='packageitinerary',
            name='stay_property',
            field=models.ForeignKey(blank=True, help_text='Stay property for the day', null=True, on_delete=django.db.models.deletion.SET_NULL, to='properties.property'),
        ),
        migrations.AlterField(
            model_name='packageitinerary',
            name='title',
            field=models.CharField(help_text='Title of the itinerary day', max_length=255),
        ),
        migrations.AlterField(
            model_name='packageitinerary',
            name='to_location',
            field=models.CharField(blank=True, help_text='Destination location', max_length=255),
        ),
        migrations.AlterField(
            model_name='packageitinerary',
            name='transport_type',
            field=models.CharField(blank=True, choices=[('cab', 'Cab'), ('boat', 'Boat'), ('train', 'Train'), ('flight', 'Flight'), ('self', 'Self Drive')], help_text='Type of transport', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='packageitinerary',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated'),
        ),
        migrations.AlterField(
            model_name='packagetransfer',
            name='cab_category',
            field=models.ForeignKey(blank=True, help_text='Related cab category', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='package_transfers', to='cabs.cabcategory'),
        ),
        migrations.AlterField(
            model_name='packagetransfer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created'),
        ),
        migrations.AlterField(
            model_name='packagetransfer',
            name='description',
            field=models.TextField(help_text='Description of the transfer'),
        ),
        migrations.AlterField(
            model_name='packagetransfer',
            name='itinerary_day',
            field=models.ForeignKey(blank=True, help_text='Related itinerary day', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers', to='packages.packageitinerary'),
        ),
        migrations.AlterField(
            model_name='packagetransfer',
            name='package',
            field=models.ForeignKey(help_text='Related holiday package', on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='packages.holidaypackage'),
        ),
        migrations.AlterField(
            model_name='packagetransfer',
            name='transport_type',
            field=models.CharField(choices=[('cab', 'Cab'), ('boat', 'Boat'), ('train', 'Train'), ('flight', 'Flight')], help_text='Type of transport', max_length=20),
        ),
        migrations.AlterField(
            model_name='packagetransfer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated'),
        ),
    ]
