# Generated by Django 4.2.16 on 2026-01-30 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0004_alter_holidaypackage_base_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('name', models.CharField(help_text='Name of the theme', max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Package Theme',
                'verbose_name_plural': 'Package Themes',
            },
        ),
        migrations.AddField(
            model_name='holidaypackage',
            name='themes',
            field=models.ManyToManyField(blank=True, help_text='Themes associated with the package', related_name='packages', to='packages.packagetheme'),
        ),
    ]
