# Generated by Django 4.2.16 on 2026-01-30 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0005_packagetheme_holidaypackage_themes'),
    ]

    operations = [
        migrations.AddField(
            model_name='holidaypackage',
            name='subtitle',
            field=models.CharField(blank=True, help_text='Subtitle or promotional tag (e.g. Free Ticket)', max_length=255, null=True),
        ),
    ]
