# Generated by Django 4.2.16 on 2026-01-29 10:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookings', '0004_alter_booking_amount_paid_alter_booking_booking_type_and_more'),
        ('coupons', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='code',
            field=models.CharField(help_text='Unique coupon code', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, help_text='Discount amount for the coupon', max_digits=10),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='valid_from',
            field=models.DateField(help_text='Start date for coupon validity'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='valid_to',
            field=models.DateField(help_text='End date for coupon validity'),
        ),
        migrations.AlterField(
            model_name='couponusage',
            name='booking',
            field=models.ForeignKey(help_text='Related booking', on_delete=django.db.models.deletion.CASCADE, to='bookings.booking'),
        ),
        migrations.AlterField(
            model_name='couponusage',
            name='coupon',
            field=models.ForeignKey(help_text='Used coupon', on_delete=django.db.models.deletion.CASCADE, to='coupons.coupon'),
        ),
        migrations.AlterField(
            model_name='couponusage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created'),
        ),
        migrations.AlterField(
            model_name='couponusage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated'),
        ),
        migrations.AlterField(
            model_name='couponusage',
            name='user',
            field=models.ForeignKey(help_text='User who used the coupon', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
