# Generated by Django 4.2.16 on 2026-01-28 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_faq'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faq',
            options={'ordering': ['location', 'question', 'title'], 'verbose_name': 'FAQ', 'verbose_name_plural': 'FAQs'},
        ),
        migrations.RemoveField(
            model_name='faq',
            name='name',
        ),
        migrations.AddField(
            model_name='faq',
            name='question',
            field=models.CharField(default='Wayanad', help_text='e.g., Which are the famous places to visit in Wayanad?', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='faq',
            name='title',
            field=models.CharField(default='FAQ Question', help_text='e.g., Edakkal Caves', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='faq',
            name='description',
            field=models.TextField(help_text='Detailed description of the place or answer'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='location',
            field=models.CharField(help_text='e.g., Wayanad', max_length=255),
        ),
    ]
