# Generated by Django 4.2.16 on 2026-01-28 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0003_alter_faq_options_remove_faq_name_faq_question_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faq',
            options={'ordering': ['location', 'question'], 'verbose_name': 'FAQ Group', 'verbose_name_plural': 'FAQ Groups'},
        ),
        migrations.RemoveField(
            model_name='faq',
            name='description',
        ),
        migrations.RemoveField(
            model_name='faq',
            name='title',
        ),
        migrations.CreateModel(
            name='FAQItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(help_text='e.g., Edakkal Caves', max_length=255)),
                ('description', models.TextField(help_text='Detailed description of the place or answer')),
                ('order', models.PositiveIntegerField(default=0, help_text='Order of display')),
                ('faq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='support.faq')),
            ],
            options={
                'verbose_name': 'FAQ Item',
                'verbose_name_plural': 'FAQ Items',
                'ordering': ['order', 'id'],
            },
        ),
    ]
