# Generated by Django 4.2.16 on 2026-01-29 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_alter_booking_amount_paid_alter_booking_booking_type_and_more'),
        ('support', '0004_alter_faq_options_remove_faq_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated'),
        ),
        migrations.AlterField(
            model_name='faqitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created'),
        ),
        migrations.AlterField(
            model_name='faqitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated'),
        ),
        migrations.AlterField(
            model_name='supportrequest',
            name='booking',
            field=models.ForeignKey(help_text='Related booking', on_delete=django.db.models.deletion.CASCADE, to='bookings.booking'),
        ),
        migrations.AlterField(
            model_name='supportrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created'),
        ),
        migrations.AlterField(
            model_name='supportrequest',
            name='request_type',
            field=models.CharField(help_text='Type of support request', max_length=50),
        ),
        migrations.AlterField(
            model_name='supportrequest',
            name='status',
            field=models.CharField(help_text='Status of the request', max_length=20),
        ),
        migrations.AlterField(
            model_name='supportrequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated'),
        ),
        migrations.AlterField(
            model_name='supporttimeline',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created'),
        ),
        migrations.AlterField(
            model_name='supporttimeline',
            name='message',
            field=models.TextField(help_text='Message content'),
        ),
        migrations.AlterField(
            model_name='supporttimeline',
            name='support_request',
            field=models.ForeignKey(help_text='Related support request', on_delete=django.db.models.deletion.CASCADE, related_name='timeline', to='support.supportrequest'),
        ),
        migrations.AlterField(
            model_name='supporttimeline',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated'),
        ),
    ]
