# Generated by Django 4.2.16 on 2026-01-29 10:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cabs', '0003_alter_cab_base_price_alter_cab_category_and_more'),
        ('houseboats', '0002_alter_houseboat_base_price_per_night_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('packages', '0004_alter_holidaypackage_base_price_and_more'),
        ('travellers', '0002_alter_traveller_created_at_alter_traveller_dob_and_more'),
        ('properties', '0007_alter_amenity_created_at_alter_amenity_icon_and_more'),
        ('activities', '0003_alter_activity_base_price_alter_activity_created_at_and_more'),
        ('bookings', '0003_booking_company_address_booking_company_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Amount paid so far', max_digits=12),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_type',
            field=models.CharField(choices=[('stay', 'Stay'), ('package', 'Package'), ('activity', 'Activity'), ('cab', 'Cab'), ('houseboat', 'Houseboat')], help_text='Type of booking', max_length=20),
        ),
        migrations.AlterField(
            model_name='booking',
            name='company_address',
            field=models.TextField(blank=True, help_text='Company address for GST invoice'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='company_name',
            field=models.CharField(blank=True, help_text='Company name for GST invoice', max_length=255),
        ),
        migrations.AlterField(
            model_name='booking',
            name='country_code',
            field=models.CharField(blank=True, help_text='Country code for the phone number', max_length=10),
        ),
        migrations.AlterField(
            model_name='booking',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='email',
            field=models.EmailField(blank=True, help_text='Email address of the contact person', max_length=254),
        ),
        migrations.AlterField(
            model_name='booking',
            name='full_name',
            field=models.CharField(blank=True, help_text='Full name of the contact person', max_length=255),
        ),
        migrations.AlterField(
            model_name='booking',
            name='gst_number',
            field=models.CharField(blank=True, help_text='GST number if applicable', max_length=50),
        ),
        migrations.AlterField(
            model_name='booking',
            name='is_gst_required',
            field=models.BooleanField(default=False, help_text='Designates whether GST is required'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='phone',
            field=models.CharField(blank=True, help_text='Phone number of the contact person', max_length=20),
        ),
        migrations.AlterField(
            model_name='booking',
            name='special_requests',
            field=models.TextField(blank=True, help_text='Any special requests from the user'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], help_text='Status of the booking', max_length=20),
        ),
        migrations.AlterField(
            model_name='booking',
            name='title',
            field=models.CharField(blank=True, help_text='Title of the contact person', max_length=10),
        ),
        migrations.AlterField(
            model_name='booking',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, help_text='Total amount for the booking', max_digits=12),
        ),
        migrations.AlterField(
            model_name='booking',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(help_text='User who made the booking', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bookingitem',
            name='activity',
            field=models.ForeignKey(blank=True, help_text='Related activity', null=True, on_delete=django.db.models.deletion.SET_NULL, to='activities.activity'),
        ),
        migrations.AlterField(
            model_name='bookingitem',
            name='adults',
            field=models.PositiveIntegerField(default=1, help_text='Number of adults'),
        ),
        migrations.AlterField(
            model_name='bookingitem',
            name='booking',
            field=models.ForeignKey(help_text='Related booking', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='bookings.booking'),
        ),
        migrations.AlterField(
            model_name='bookingitem',
            name='cab',
            field=models.ForeignKey(blank=True, help_text='Related cab', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cabs.cab'),
        ),
        migrations.AlterField(
            model_name='bookingitem',
            name='check_in',
            field=models.DateField(blank=True, help_text='Check-in date', null=True),
        ),
        migrations.AlterField(
            model_name='bookingitem',
            name='check_out',
            field=models.DateField(blank=True, help_text='Check-out date', null=True),
        ),
        migrations.AlterField(
            model_name='bookingitem',
            name='children',
            field=models.PositiveIntegerField(default=0, help_text='Number of children'),
        ),
        migrations.AlterField(
            model_name='bookingitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created'),
        ),
        migrations.AlterField(
            model_name='bookingitem',
            name='houseboat',
            field=models.ForeignKey(blank=True, help_text='Related houseboat', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_items', to='houseboats.houseboat'),
        ),
        migrations.AlterField(
            model_name='bookingitem',
            name='package',
            field=models.ForeignKey(blank=True, help_text='Related holiday package', null=True, on_delete=django.db.models.deletion.SET_NULL, to='packages.holidaypackage'),
        ),
        migrations.AlterField(
            model_name='bookingitem',
            name='property',
            field=models.ForeignKey(blank=True, help_text='Related property', null=True, on_delete=django.db.models.deletion.SET_NULL, to='properties.property'),
        ),
        migrations.AlterField(
            model_name='bookingitem',
            name='room_type',
            field=models.ForeignKey(blank=True, help_text='Related room type', null=True, on_delete=django.db.models.deletion.SET_NULL, to='properties.roomtype'),
        ),
        migrations.AlterField(
            model_name='bookingitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated'),
        ),
        migrations.AlterField(
            model_name='bookingtraveller',
            name='booking',
            field=models.ForeignKey(help_text='Related booking', on_delete=django.db.models.deletion.CASCADE, to='bookings.booking'),
        ),
        migrations.AlterField(
            model_name='bookingtraveller',
            name='is_primary',
            field=models.BooleanField(default=False, help_text='Designates whether this is the primary traveller'),
        ),
        migrations.AlterField(
            model_name='bookingtraveller',
            name='traveller',
            field=models.ForeignKey(help_text='Related traveller', on_delete=django.db.models.deletion.CASCADE, to='travellers.traveller'),
        ),
    ]
