# Generated by Django 4.2.16 on 2026-01-29 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0002_alter_coupon_code_alter_coupon_created_at_and_more'),
        ('bookings', '0004_alter_booking_amount_paid_alter_booking_booking_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='coupon',
            field=models.ForeignKey(blank=True, help_text='Applied coupon', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='coupons.coupon'),
        ),
    ]
