# Generated by Django 4.2.16 on 2026-01-29 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_booking_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, help_text='Date and time when the booking was cancelled', null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='refund_status',
            field=models.CharField(choices=[('none', 'No Refund'), ('processing', 'Processing'), ('processed', 'Processed'), ('no_refund_due', 'No Refund Due')], default='none', help_text='Status of the refund', max_length=20),
        ),
    ]
