# Generated by Django 4.2.16 on 2026-01-29 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_booking_cancelled_at_booking_refund_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='pricing_breakdown',
            field=models.JSONField(blank=True, default=dict, help_text='JSON snapshot of pricing details (base, tax, discount, fees)'),
        ),
    ]
