# Generated by Django 4.2.16 on 2026-01-30 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0013_property_latitude_property_longitude'),
        ('bookings', '0007_booking_pricing_breakdown'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingitem',
            name='room_option',
            field=models.ForeignKey(blank=True, help_text='Selected room option (pricing plan)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='properties.roomoption'),
        ),
    ]
