# Generated by Django 4.2.16 on 2026-01-30 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0008_bookingitem_room_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='insurance_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Amount for travel insurance', max_digits=10),
        ),
        migrations.AddField(
            model_name='booking',
            name='is_insurance_opted',
            field=models.BooleanField(default=False, help_text='Designates whether travel insurance is opted'),
        ),
        migrations.AddField(
            model_name='bookingitem',
            name='full_time_ac_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Amount for full time AC', max_digits=10),
        ),
        migrations.AddField(
            model_name='bookingitem',
            name='is_full_time_ac_opted',
            field=models.BooleanField(default=False, help_text='Designates whether full time AC is opted'),
        ),
    ]
