# Generated by Django 4.2.16 on 2026-01-30 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0009_booking_insurance_amount_booking_is_insurance_opted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='part_payment_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Amount to be paid now if part payment is selected', max_digits=12),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_option',
            field=models.CharField(choices=[('full', 'Full Payment'), ('part', 'Part Payment')], default='full', help_text='Selected payment option', max_length=10),
        ),
        migrations.AddField(
            model_name='bookingitem',
            name='drop_location',
            field=models.CharField(blank=True, help_text='Drop location for cabs', max_length=255),
        ),
        migrations.AddField(
            model_name='bookingitem',
            name='pickup_datetime',
            field=models.DateTimeField(blank=True, help_text='Pickup date and time for cabs', null=True),
        ),
        migrations.AddField(
            model_name='bookingitem',
            name='pickup_location',
            field=models.CharField(blank=True, help_text='Pickup location for cabs', max_length=255),
        ),
        migrations.AddField(
            model_name='bookingitem',
            name='trip_type',
            field=models.CharField(blank=True, help_text='Type of trip (e.g. Airport Transfer)', max_length=50),
        ),
    ]
