# Generated by Django 4.2.16 on 2026-01-28 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0005_amenity_discount_remove_property_discount_percent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HouseBoat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('location', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('base_price_per_night', models.DecimalField(decimal_places=2, max_digits=12)),
                ('rating', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('review_count', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('discount', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='houseboats', to='properties.discount')),
            ],
            options={
                'verbose_name': 'Houseboat',
                'verbose_name_plural': 'Houseboats',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HouseBoatTiming',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('check_in_time', models.TimeField()),
                ('check_out_time', models.TimeField()),
                ('cruise_start_time', models.TimeField()),
                ('cruise_end_time', models.TimeField()),
                ('houseboat', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='timing', to='houseboats.houseboat')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HouseBoatSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bedrooms', models.PositiveSmallIntegerField()),
                ('bathrooms', models.PositiveSmallIntegerField()),
                ('max_guests', models.PositiveSmallIntegerField()),
                ('ac_type', models.CharField(choices=[('full_time', 'Full Time'), ('night_only', 'Night Only'), ('none', 'None')], max_length=20)),
                ('cruise_type', models.CharField(choices=[('day_cruise', 'Day Cruise'), ('overnight_cruise', 'Overnight Cruise')], max_length=20)),
                ('houseboat', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='specification', to='houseboats.houseboat')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HouseBoatRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('boarding_point', models.CharField(max_length=255)),
                ('drop_point', models.CharField(max_length=255)),
                ('route_description', models.TextField()),
                ('houseboat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='houseboats.houseboat')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HouseBoatPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cancellation_policy', models.TextField()),
                ('refund_policy', models.TextField()),
                ('house_rules', models.TextField()),
                ('houseboat', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='policy', to='houseboats.houseboat')),
            ],
            options={
                'verbose_name_plural': 'Houseboat Policies',
            },
        ),
        migrations.CreateModel(
            name='HouseBoatMealPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('breakfast_included', models.BooleanField(default=True)),
                ('lunch_included', models.BooleanField(default=True)),
                ('dinner_included', models.BooleanField(default=True)),
                ('welcome_drink', models.BooleanField(default=True)),
                ('veg_only', models.BooleanField(default=False)),
                ('menu_description', models.TextField(blank=True)),
                ('houseboat', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='meal_plan', to='houseboats.houseboat')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HouseBoatInclusion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.TextField()),
                ('is_included', models.BooleanField(default=True)),
                ('houseboat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inclusions', to='houseboats.houseboat')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HouseBoatImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='houseboats/gallery/%Y/%m/')),
                ('is_primary', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('houseboat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='houseboats.houseboat')),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
