# Generated by Django 4.2.16 on 2026-01-29 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0007_alter_amenity_created_at_alter_amenity_icon_and_more'),
        ('houseboats', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='houseboat',
            name='base_price_per_night',
            field=models.DecimalField(decimal_places=2, help_text='Base price per night', max_digits=12),
        ),
        migrations.AlterField(
            model_name='houseboat',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created'),
        ),
        migrations.AlterField(
            model_name='houseboat',
            name='description',
            field=models.TextField(help_text='Detailed description of the houseboat'),
        ),
        migrations.AlterField(
            model_name='houseboat',
            name='discount',
            field=models.ForeignKey(blank=True, help_text='Applicable discount for the houseboat', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='houseboats', to='properties.discount'),
        ),
        migrations.AlterField(
            model_name='houseboat',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether the houseboat is active'),
        ),
        migrations.AlterField(
            model_name='houseboat',
            name='location',
            field=models.CharField(help_text='Location of the houseboat', max_length=255),
        ),
        migrations.AlterField(
            model_name='houseboat',
            name='name',
            field=models.CharField(help_text='Name of the houseboat', max_length=255),
        ),
        migrations.AlterField(
            model_name='houseboat',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Average rating of the houseboat', max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='houseboat',
            name='review_count',
            field=models.PositiveIntegerField(default=0, help_text='Total number of reviews'),
        ),
        migrations.AlterField(
            model_name='houseboat',
            name='slug',
            field=models.SlugField(help_text='Unique slug for the houseboat URL', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='houseboat',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated'),
        ),
        migrations.AlterField(
            model_name='houseboatimage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created'),
        ),
        migrations.AlterField(
            model_name='houseboatimage',
            name='houseboat',
            field=models.ForeignKey(help_text='Related houseboat', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='houseboats.houseboat'),
        ),
        migrations.AlterField(
            model_name='houseboatimage',
            name='image',
            field=models.ImageField(help_text='Image file for the houseboat', upload_to='houseboats/gallery/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='houseboatimage',
            name='is_primary',
            field=models.BooleanField(default=False, help_text='Designates whether this is the primary image'),
        ),
        migrations.AlterField(
            model_name='houseboatimage',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Ordering of the image'),
        ),
        migrations.AlterField(
            model_name='houseboatimage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated'),
        ),
        migrations.AlterField(
            model_name='houseboatinclusion',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created'),
        ),
        migrations.AlterField(
            model_name='houseboatinclusion',
            name='houseboat',
            field=models.ForeignKey(help_text='Related houseboat', on_delete=django.db.models.deletion.CASCADE, related_name='inclusions', to='houseboats.houseboat'),
        ),
        migrations.AlterField(
            model_name='houseboatinclusion',
            name='is_included',
            field=models.BooleanField(default=True, help_text='Designates whether this is an inclusion'),
        ),
        migrations.AlterField(
            model_name='houseboatinclusion',
            name='text',
            field=models.TextField(help_text='Inclusion/Exclusion text'),
        ),
        migrations.AlterField(
            model_name='houseboatinclusion',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated'),
        ),
        migrations.AlterField(
            model_name='houseboatmealplan',
            name='breakfast_included',
            field=models.BooleanField(default=True, help_text='Designates whether breakfast is included'),
        ),
        migrations.AlterField(
            model_name='houseboatmealplan',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created'),
        ),
        migrations.AlterField(
            model_name='houseboatmealplan',
            name='dinner_included',
            field=models.BooleanField(default=True, help_text='Designates whether dinner is included'),
        ),
        migrations.AlterField(
            model_name='houseboatmealplan',
            name='houseboat',
            field=models.OneToOneField(help_text='Related houseboat', on_delete=django.db.models.deletion.CASCADE, related_name='meal_plan', to='houseboats.houseboat'),
        ),
        migrations.AlterField(
            model_name='houseboatmealplan',
            name='lunch_included',
            field=models.BooleanField(default=True, help_text='Designates whether lunch is included'),
        ),
        migrations.AlterField(
            model_name='houseboatmealplan',
            name='menu_description',
            field=models.TextField(blank=True, help_text='Description of the menu'),
        ),
        migrations.AlterField(
            model_name='houseboatmealplan',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated'),
        ),
        migrations.AlterField(
            model_name='houseboatmealplan',
            name='veg_only',
            field=models.BooleanField(default=False, help_text='Designates whether only vegetarian food is served'),
        ),
        migrations.AlterField(
            model_name='houseboatmealplan',
            name='welcome_drink',
            field=models.BooleanField(default=True, help_text='Designates whether welcome drink is included'),
        ),
        migrations.AlterField(
            model_name='houseboatpolicy',
            name='cancellation_policy',
            field=models.TextField(help_text='Cancellation policy'),
        ),
        migrations.AlterField(
            model_name='houseboatpolicy',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created'),
        ),
        migrations.AlterField(
            model_name='houseboatpolicy',
            name='house_rules',
            field=models.TextField(help_text='House rules'),
        ),
        migrations.AlterField(
            model_name='houseboatpolicy',
            name='houseboat',
            field=models.OneToOneField(help_text='Related houseboat', on_delete=django.db.models.deletion.CASCADE, related_name='policy', to='houseboats.houseboat'),
        ),
        migrations.AlterField(
            model_name='houseboatpolicy',
            name='refund_policy',
            field=models.TextField(help_text='Refund policy'),
        ),
        migrations.AlterField(
            model_name='houseboatpolicy',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated'),
        ),
        migrations.AlterField(
            model_name='houseboatroute',
            name='boarding_point',
            field=models.CharField(help_text='Boarding point for the houseboat', max_length=255),
        ),
        migrations.AlterField(
            model_name='houseboatroute',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created'),
        ),
        migrations.AlterField(
            model_name='houseboatroute',
            name='drop_point',
            field=models.CharField(help_text='Drop point for the houseboat', max_length=255),
        ),
        migrations.AlterField(
            model_name='houseboatroute',
            name='houseboat',
            field=models.ForeignKey(help_text='Related houseboat', on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='houseboats.houseboat'),
        ),
        migrations.AlterField(
            model_name='houseboatroute',
            name='route_description',
            field=models.TextField(help_text='Description of the route'),
        ),
        migrations.AlterField(
            model_name='houseboatroute',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated'),
        ),
        migrations.AlterField(
            model_name='houseboatspecification',
            name='ac_type',
            field=models.CharField(choices=[('full_time', 'Full Time'), ('night_only', 'Night Only'), ('none', 'None')], help_text='Type of air conditioning', max_length=20),
        ),
        migrations.AlterField(
            model_name='houseboatspecification',
            name='bathrooms',
            field=models.PositiveSmallIntegerField(help_text='Number of bathrooms'),
        ),
        migrations.AlterField(
            model_name='houseboatspecification',
            name='bedrooms',
            field=models.PositiveSmallIntegerField(help_text='Number of bedrooms'),
        ),
        migrations.AlterField(
            model_name='houseboatspecification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created'),
        ),
        migrations.AlterField(
            model_name='houseboatspecification',
            name='cruise_type',
            field=models.CharField(choices=[('day_cruise', 'Day Cruise'), ('overnight_cruise', 'Overnight Cruise')], help_text='Type of cruise', max_length=20),
        ),
        migrations.AlterField(
            model_name='houseboatspecification',
            name='houseboat',
            field=models.OneToOneField(help_text='Related houseboat', on_delete=django.db.models.deletion.CASCADE, related_name='specification', to='houseboats.houseboat'),
        ),
        migrations.AlterField(
            model_name='houseboatspecification',
            name='max_guests',
            field=models.PositiveSmallIntegerField(help_text='Maximum number of guests'),
        ),
        migrations.AlterField(
            model_name='houseboatspecification',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated'),
        ),
        migrations.AlterField(
            model_name='houseboattiming',
            name='check_in_time',
            field=models.TimeField(help_text='Check-in time'),
        ),
        migrations.AlterField(
            model_name='houseboattiming',
            name='check_out_time',
            field=models.TimeField(help_text='Check-out time'),
        ),
        migrations.AlterField(
            model_name='houseboattiming',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created'),
        ),
        migrations.AlterField(
            model_name='houseboattiming',
            name='cruise_end_time',
            field=models.TimeField(help_text='Cruise end time'),
        ),
        migrations.AlterField(
            model_name='houseboattiming',
            name='cruise_start_time',
            field=models.TimeField(help_text='Cruise start time'),
        ),
        migrations.AlterField(
            model_name='houseboattiming',
            name='houseboat',
            field=models.OneToOneField(help_text='Related houseboat', on_delete=django.db.models.deletion.CASCADE, related_name='timing', to='houseboats.houseboat'),
        ),
        migrations.AlterField(
            model_name='houseboattiming',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated'),
        ),
    ]
