# Generated by Django 4.2.16 on 2026-01-30 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houseboats', '0002_alter_houseboat_base_price_per_night_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='houseboat',
            name='extra_guest_price_adult',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Price per extra adult', max_digits=10),
        ),
        migrations.AddField(
            model_name='houseboat',
            name='extra_guest_price_child',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Price per extra child', max_digits=10),
        ),
        migrations.AddField(
            model_name='houseboat',
            name='full_time_ac_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Price for full time AC upgrade per night', max_digits=10),
        ),
    ]
