# Generated by Django 4.2.16 on 2026-01-29 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0007_alter_amenity_created_at_alter_amenity_icon_and_more'),
        ('activities', '0002_alter_activity_options_activity_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='base_price',
            field=models.DecimalField(decimal_places=2, help_text='Base price for the activity', max_digits=12),
        ),
        migrations.AlterField(
            model_name='activity',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='description',
            field=models.TextField(help_text='Detailed description of the activity'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Easy'), ('moderate', 'Moderate'), ('hard', 'Hard')], help_text='Difficulty level of the activity', max_length=20),
        ),
        migrations.AlterField(
            model_name='activity',
            name='discount',
            field=models.ForeignKey(blank=True, help_text='Applicable discount for the activity', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='properties.discount'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='duration_days',
            field=models.PositiveSmallIntegerField(help_text='Duration of the activity in days'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='duration_nights',
            field=models.PositiveSmallIntegerField(default=0, help_text='Duration of the activity in nights'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='group_size',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Maximum group size for the activity', null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether the activity is active and visible'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='location',
            field=models.CharField(help_text='Location where the activity takes place', max_length=255),
        ),
        migrations.AlterField(
            model_name='activity',
            name='max_age',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Maximum age limit for the activity', null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='min_age',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Minimum age requirement for the activity', null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Average rating of the activity', max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='review_count',
            field=models.PositiveIntegerField(default=0, help_text='Total number of reviews'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='short_description',
            field=models.TextField(help_text='Brief summary of the activity'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='slug',
            field=models.SlugField(help_text='Unique slug for the activity URL', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='title',
            field=models.CharField(help_text='The name of the activity', max_length=255),
        ),
        migrations.AlterField(
            model_name='activity',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated'),
        ),
        migrations.AlterField(
            model_name='activityfeature',
            name='activity',
            field=models.ForeignKey(help_text='Related activity', on_delete=django.db.models.deletion.CASCADE, related_name='features', to='activities.activity'),
        ),
        migrations.AlterField(
            model_name='activityfeature',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created'),
        ),
        migrations.AlterField(
            model_name='activityfeature',
            name='feature_type',
            field=models.CharField(choices=[('sightseeing', 'Sightseeing'), ('stay', 'Stay'), ('transport', 'Transport'), ('meals', 'Meals')], help_text='Type of the feature', max_length=20),
        ),
        migrations.AlterField(
            model_name='activityfeature',
            name='is_included',
            field=models.BooleanField(default=True, help_text='Designates whether the feature is included'),
        ),
        migrations.AlterField(
            model_name='activityfeature',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated'),
        ),
        migrations.AlterField(
            model_name='activityhighlight',
            name='activity',
            field=models.ForeignKey(help_text='Related activity', on_delete=django.db.models.deletion.CASCADE, related_name='highlights', to='activities.activity'),
        ),
        migrations.AlterField(
            model_name='activityhighlight',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created'),
        ),
        migrations.AlterField(
            model_name='activityhighlight',
            name='text',
            field=models.TextField(help_text='Highlight text'),
        ),
        migrations.AlterField(
            model_name='activityhighlight',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated'),
        ),
        migrations.AlterField(
            model_name='activityimage',
            name='activity',
            field=models.ForeignKey(help_text='Related activity', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='activities.activity'),
        ),
        migrations.AlterField(
            model_name='activityimage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created'),
        ),
        migrations.AlterField(
            model_name='activityimage',
            name='image',
            field=models.ImageField(help_text='Image file for the activity', upload_to='activities/gallery/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='activityimage',
            name='is_primary',
            field=models.BooleanField(default=False, help_text='Designates whether this is the primary image'),
        ),
        migrations.AlterField(
            model_name='activityimage',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Ordering of the image'),
        ),
        migrations.AlterField(
            model_name='activityimage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated'),
        ),
        migrations.AlterField(
            model_name='activityinclusion',
            name='activity',
            field=models.ForeignKey(help_text='Related activity', on_delete=django.db.models.deletion.CASCADE, related_name='inclusions', to='activities.activity'),
        ),
        migrations.AlterField(
            model_name='activityinclusion',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created'),
        ),
        migrations.AlterField(
            model_name='activityinclusion',
            name='is_included',
            field=models.BooleanField(default=True, help_text='Designates whether this is an inclusion'),
        ),
        migrations.AlterField(
            model_name='activityinclusion',
            name='text',
            field=models.TextField(help_text='Inclusion/Exclusion text'),
        ),
        migrations.AlterField(
            model_name='activityinclusion',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated'),
        ),
        migrations.AlterField(
            model_name='activityitinerary',
            name='activity',
            field=models.ForeignKey(help_text='Related activity', on_delete=django.db.models.deletion.CASCADE, related_name='itinerary', to='activities.activity'),
        ),
        migrations.AlterField(
            model_name='activityitinerary',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created'),
        ),
        migrations.AlterField(
            model_name='activityitinerary',
            name='day_number',
            field=models.PositiveSmallIntegerField(help_text='Day number of the itinerary'),
        ),
        migrations.AlterField(
            model_name='activityitinerary',
            name='description',
            field=models.TextField(help_text='Description of the itinerary day'),
        ),
        migrations.AlterField(
            model_name='activityitinerary',
            name='image',
            field=models.ImageField(blank=True, help_text='Image for the itinerary day', null=True, upload_to='activities/itinerary/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='activityitinerary',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, help_text='Ordering of the itinerary day'),
        ),
        migrations.AlterField(
            model_name='activityitinerary',
            name='title',
            field=models.CharField(help_text='Title of the itinerary day', max_length=255),
        ),
        migrations.AlterField(
            model_name='activityitinerary',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated'),
        ),
        migrations.AlterField(
            model_name='activitypolicy',
            name='activity',
            field=models.OneToOneField(help_text='Related activity', on_delete=django.db.models.deletion.CASCADE, related_name='policy', to='activities.activity'),
        ),
        migrations.AlterField(
            model_name='activitypolicy',
            name='cancellation_policy',
            field=models.TextField(help_text='Cancellation policy for the activity'),
        ),
        migrations.AlterField(
            model_name='activitypolicy',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created'),
        ),
        migrations.AlterField(
            model_name='activitypolicy',
            name='safety_guidelines',
            field=models.TextField(help_text='Safety guidelines for the activity'),
        ),
        migrations.AlterField(
            model_name='activitypolicy',
            name='terms_and_conditions',
            field=models.TextField(help_text='Terms and conditions for the activity'),
        ),
        migrations.AlterField(
            model_name='activitypolicy',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated'),
        ),
    ]
