# Generated by Django 4.2.16 on 2026-01-30 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_alter_activity_base_price_alter_activity_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('name', models.CharField(help_text='Name of the activity type', max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Activity Type',
                'verbose_name_plural': 'Activity Types',
            },
        ),
        migrations.AddField(
            model_name='activity',
            name='types',
            field=models.ManyToManyField(blank=True, help_text='Types of activity', related_name='activities', to='activities.activitytype'),
        ),
    ]
